name: 'publish'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish-tauri:
    permissions:
      contents: write
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: '--target x86_64-unknown-linux-gnu'
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            libssl-dev \
            build-essential \
            librsvg2-dev \
            libxdo-dev \
            libgtk-3-dev

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        shell: cmd
        run: |
          curl -L -o "src-tauri\windows\vc_redist.x64.exe" https://aka.ms/vs/17/release/vc_redist.x64.exe

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        shell: bash
        run: npm i

      - uses: tauri-apps/tauri-action@v0
        with:
          tagName: FurPlayer-v__VERSION__
          releaseName: 'FurPlayer v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


