name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Node.js dependencies
      run: npm install

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Tauri CLI
      run: cargo install tauri-cli

    - name: Build Tauri project
      run: npm run tauri build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-build-${{ matrix.os }}
        path: src-tauri/target/release/bundle/